"""
Django settings for multibot project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-34&5nhw6loh$)01mq$b*y&kism#s-9t_-i+6v-y8q1!a3r-+!d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bots.apps.BotsConfig',
    # 'bots',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'multibot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'bots']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multibot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        # 使用的数据库引擎：MySQL
        "ENGINE": "django.db.backends.mysql",

        # 数据库名称（与你实际创建的 MySQL 数据库名一致）
        "NAME": "ce",

        # 登录数据库的用户名
        "USER": "ce",

        # 用户密码（确保在生产环境中使用强密码）
        "PASSWORD": "12345678",

        # 数据库主机地址，通常本地为 127.0.0.1，远程部署时可填服务器 IP
        "HOST": "127.0.0.1",

        # 数据库端口号（MySQL 默认端口是 3306）
        "PORT": "3306",

        # 可选参数配置
        "OPTIONS": {
            # 初始化时执行的 SQL 语句，开启严格模式，避免错误地将错误值插入数据库
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",

            # 设置连接数据库的超时时间（单位：秒），避免长时间等待
            "connect_timeout": 10,

            # 设置字符集为 utf8mb4，支持 Emoji 和所有 Unicode 字符
            "charset": "utf8mb4",

            # 设置从数据库读取数据的超时时间（单位：秒）
            "read_timeout": 10,

            # 设置向数据库写入数据的超时时间（单位：秒）
            "write_timeout": 10,

            # 自动提交事务（True 表示每次执行 SQL 后会自动 commit）
            "autocommit": True,
        },

        # 数据库连接复用时间（单位：秒）
        # None 表示连接永久复用（直到连接断开），减少频繁重连开销，适合持续运行的服务
        # 若设置为 60，表示 Django 会在 60 秒后主动断开连接并重建
        "CONN_MAX_AGE": None
    }
}


REDIS_CONFIG = {
    'host': 'localhost',
    'port': 6379,
    'db': 0,
    'password': ''  # 如果没有密码，可以设置为 None
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
