# Generated by Django 5.2 for the initial bot template.
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("bot_enabled", models.BooleanField(default=False)),
                ("welcome_enabled", models.BooleanField(default=True)),
                ("welcome_message", models.TextField(default="欢迎 {first_name} 加入 {group_title}！")),
                ("tron_monitor_enabled", models.BooleanField(default=False)),
                ("tron_poll_interval", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Bot settings"},
        ),
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("group_type", models.CharField(choices=[("group", "Group"), ("supergroup", "Supergroup"), ("channel", "Channel")], max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("language_code", models.CharField(blank=True, max_length=16)),
                ("is_bot", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.CreateModel(
            name="TronAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(db_index=True, max_length=34, unique=True)),
                ("label", models.CharField(blank=True, max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                ("balance_sun", models.BigIntegerField(default=0)),
                ("last_transaction_id", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("ok", "OK"), ("error", "Error")], default="pending", max_length=16)),
                ("last_error", models.TextField(blank=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
