# Generated by Django 5.2.17 on 2026-08-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('first_spoke_at', models.DateTimeField(auto_now_add=True)),
                ('last_spoke_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botcore.telegramgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='botcore.telegramuser')),
            ],
            options={
                'ordering': ['-last_spoke_at'],
                'indexes': [models.Index(fields=['group', 'last_spoke_at'], name='tg_member_group_last_idx'), models.Index(fields=['user', 'last_spoke_at'], name='tg_member_user_last_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_telegram_group_member')],
            },
        ),
    ]
