# Generated by Django 5.2.17 on 2026-08-15 02:25

import django.db.models.deletion
from django.db import migrations, models


def migrate_default_bot(apps, schema_editor):
    BotSettings = apps.get_model('botcore', 'BotSettings')
    TelegramBot = apps.get_model('botcore', 'TelegramBot')
    TelegramBotUser = apps.get_model('botcore', 'TelegramBotUser')
    TelegramGroupMember = apps.get_model('botcore', 'TelegramGroupMember')
    TelegramUser = apps.get_model('botcore', 'TelegramUser')

    settings = BotSettings.objects.filter(singleton_key=1).first()
    bot = TelegramBot.objects.create(
        name='默认机器人',
        token_env_var='TELEGRAM_BOT_TOKEN',
        enabled=settings.bot_enabled if settings else False,
        welcome_enabled=settings.welcome_enabled if settings else True,
        welcome_message=(
            settings.welcome_message
            if settings
            else '欢迎 {first_name} 加入 {group_title}！'
        ),
    )
    TelegramGroupMember.objects.update(bot=bot)
    TelegramBotUser.objects.bulk_create([
        TelegramBotUser(bot=bot, user=user, message_count=user.message_count)
        for user in TelegramUser.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0002_telegramgroupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('token_env_var', models.CharField(default='TELEGRAM_BOT_TOKEN', max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('welcome_enabled', models.BooleanField(default=True)),
                ('welcome_message', models.TextField(default='欢迎 {first_name} 加入 {group_title}！')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBotButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=500)),
                ('row', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['row', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='telegramgroupmember',
            name='unique_telegram_group_member',
        ),
        migrations.AddField(
            model_name='telegramgroupmember',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='botcore.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrambotbutton',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='botcore.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='botcore.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='botcore.telegramuser'),
        ),
        migrations.RunPython(migrate_default_bot, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='botsettings',
            name='bot_enabled',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='welcome_enabled',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='welcome_message',
        ),
        migrations.AlterField(
            model_name='telegramgroupmember',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='botcore.telegrambot'),
        ),
        migrations.AddConstraint(
            model_name='telegramgroupmember',
            constraint=models.UniqueConstraint(fields=('bot', 'group', 'user'), name='unique_telegram_bot_group_member'),
        ),
        migrations.AddConstraint(
            model_name='telegrambotbutton',
            constraint=models.UniqueConstraint(fields=('bot', 'row', 'position'), name='unique_telegram_bot_button_position'),
        ),
        migrations.AddConstraint(
            model_name='telegrambotuser',
            constraint=models.UniqueConstraint(fields=('bot', 'user'), name='unique_telegram_bot_user'),
        ),
    ]
