# Generated by Django 5.2.17 on 2026-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0003_telegrambot_telegrambotbutton_telegrambotuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='tron_api_key_env_var',
            field=models.CharField(default='TRONGRID_API_KEY', max_length=64),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='tron_api_url',
            field=models.URLField(default='https://api.trongrid.io', max_length=255),
        ),
    ]
