# Generated by Django 5.2.17 on 2026-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0004_botsettings_tron_api_key_env_var_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='tron_api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
