# Generated by Django 5.2.17 on 2026-08-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0005_botsettings_tron_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='botcore.telegrambot'),
        ),
    ]
