# Generated by Django 5.2.17 on 2026-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0006_telegrambot_cloned_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='clone_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
