# Generated by Django 5.2.17 on 2026-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0007_telegrambot_clone_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('code_sent', 'Code sent'), ('password_required', 'Password required'), ('logged_in', 'Logged in'), ('session_expired', 'Session expired'), ('error', 'Error')], default='pending', max_length=32)),
                ('phone_code_hash', models.TextField(blank=True)),
                ('session_string', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='botsettings',
            name='telegram_api_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='telegram_api_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
