# Generated by Django 5.2.17 on 2026-09-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcore', '0011_tronblockcursor_trontransferevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tronaddress',
            name='permission_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tronaddress',
            name='resource_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TronAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('resource_changed', 'Resource changed'), ('authorization_changed', 'Authorization changed'), ('permission_changed', 'Permission changed')], db_index=True, max_length=32)),
                ('block_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('tx_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_index', models.PositiveIntegerField(default=0)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('current_value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='botcore.tronaddress')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tx_id', ''), _negated=True), fields=('address', 'alert_type', 'tx_id', 'event_index'), name='unique_tron_chain_alert')],
            },
        ),
    ]
